
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.development }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.staging }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.production }}