apiVersion: batch/v1
kind: Job
metadata:
  name: namespace-creator
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              if ! kubectl get namespace {{ .Values.namespaces.development }}; then
                kubectl create namespace {{ .Values.namespaces.development }}
              fi
              if ! kubectl get namespace {{ .Values.namespaces.staging }}; then
                kubectl create namespace {{ .Values.namespaces.staging }}
              fi
              if ! kubectl get namespace {{ .Values.namespaces.production }}; then
                kubectl create namespace {{ .Values.namespaces.production }}
              fi